FROM node:12.19-alpine

# APP
ARG PORT
ARG DEBUG_PORT
ARG API_PREFIX

# SERVICES
ARG SERVICE_ORDER_HOST
ARG SERVICE_ORDER_PORT
ARG SERVICE_PAYMENT_HOST
ARG SERVICE_PAYMENT_PORT

# ENVIRONMENT
ENV NODE_ENV development
ENV PORT $PORT
ENV DEBUG_PORT $DEBUG_PORT
ENV API_PREFIX $API_PREFIX
ENV SERVICE_ORDER_HOST $SERVICE_ORDER_HOST
ENV SERVICE_ORDER_PORT $SERVICE_ORDER_PORT
ENV SERVICE_PAYMENT_HOST $SERVICE_PAYMENT_HOST
ENV SERVICE_PAYMENT_PORT $SERVICE_PAYMENT_PORT

WORKDIR /usr/src/app

RUN apk update
RUN apk add g++ make python
RUN apk add git bash

COPY package*.json ./

# add yarn
RUN npm i yarn@latest -g --force

RUN yarn install

COPY . .

RUN yarn run build

ENTRYPOINT [ "bash", "./init.sh" ]